### ISSUE TITLE
Implement Batch Ingest HTTPD API RFC

### ISSUE THREAD

**Issue by msuhovec** [ndlib/curatend-batch#12]
As per

https://github.com/ndlib/curatend-batch/blob/master/api.md

**Comment by msuhovec** [comment]
Question: I'm assuming the that "data" directory does not have to live in the same directory space ( .i.e 'success', 'queued', 'error', 'processing'): is this true?

**Comment by msuhovec** [comment]
With respect to the job id- how should  this be created?

**Comment by msuhovec** [comment]
What jobs are in status 'ready'- those in data? If that's the case, should I perform any sort of verfication?

**Comment by dbrower** [comment]
Um. The data directory should probably be at the same level as the `success`, `queued`, etc. directories. It is important that it lives on the same filesystem as those directories, and being at the same level gives a good chance of that.

The batch system never creates job ids. The person creating a job must supply a job id. The API enforces that by not having a general purpose "create a job" endpoint. It only has a "create a job with this name" endpoint. Perhaps the spec should add a "FAIL IF JOB EXISTS" to prevent race conditions when creating a new job...

the `ready` status is the jobs in "data". No verification needs to be done for now. If a job isn't ready to be run, it will end up in the error state after being run.

**Comment by msuhovec** [comment]
GET /jobs &
GET /jobs/:id  

are done- submitted against branch issue-13

**Comment by msuhovec** [comment]
PUT /jobs/:id is done, and submitted against  branch issue-13

**Comment by msuhovec** [comment]
For the DELETE, I'm deleting it from data, error, and sucess, unless you feel otherwise.

**Comment by msuhovec** [comment]
DELETE /jobs/:id is done

**Comment by msuhovec** [comment]
POST /jobs/:jobid/queue - the order I'm looking in is data, error, success

**Comment by dbrower** [comment]
That order is fine. Hopefully a job with a given name only exists in one of those places. If not...hm.

Also, you could probably unify the job finding code and always search data, error, success, queue, and processing.

**Comment by msuhovec** [comment]
see issue #14
