### ISSUE TITLE
Capture the response body for WEBHOOK's calls

### ISSUE THREAD

**Issue by jeremyf** [ndlib/curatend-batch#16]
At present, the WEBHOOKs processing is capturing the status code but not the response body. In troubleshooting Sipity's responses, it would be helpful to have the message body; Or at least the first 3000 characters whichever is easier.

See the [following comment](https://github.com/ndlib/curatend-batch/blob/master/batchs/webhook.go#L63).

**Comment by dbrower** [comment]
I think this is done. It exists in the tag `v1.1.0`.
