### ISSUE TITLE
Run daemon as app instead of root

### ISSUE THREAD

**Issue by danhorst** [ndlib/curatend-batch#22]
Running the CurateND-batch daemon as root shouldn’t be necessary. It also introduces some environment-specific knowledge in the tasks scripts e.g. `su app -c` which makes them less portable.

- [x] Make the necessary changes to the puppet scripts to get the daemon running as the app user. This probably means switching from `upstart` to [`runit`](http://smarden.org/runit/). (Also, [Mike Perham likes `runit`](https://www.mikeperham.com/2014/07/07/use-runit/) so you know it’s good.)
- [x] Remove `su app -c` directive from task scripts

**Comment by dbrower** [comment]
@msuhovec I know we made puppet classes to use runit for bendo. What do you think about also using it for batchs?

**Comment by msuhovec** [comment]
I think it should work- can look at it Tues.
